# Generated by Django 5.1.5 on 2025-06-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resident', '0002_resident_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('total_floors', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('number', models.CharField(max_length=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.PositiveSmallIntegerField(choices=[(1, '1 persona'), (2, '2 personas')], default=1)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('num_bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='rent.building')),
                ('services', models.ManyToManyField(blank=True, related_name='departments', to='rent.service')),
            ],
            options={
                'unique_together': {('building', 'floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='departments/')),
                ('is_featured', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.department')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='resident.resident')),
            ],
        ),
    ]
