# Generated by Django 5.1.5 on 2025-06-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_lease_contrato_pdf_lease_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='transferencia', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent.lease')),
            ],
        ),
    ]
