# Generated by Django 5.1.5 on 2025-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/'),
        ),
    ]
