# Generated by Django 5.1.5 on 2025-06-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_resident_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='resident.resident')),
            ],
        ),
    ]
