# Generated by Django 5.1.5 on 2025-06-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.usuario')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name1', models.CharField(max_length=100)),
                ('last_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_document', models.CharField(max_length=20, unique=True)),
                ('oficio', models.CharField(choices=[('INF', 'Informática'), ('PLO', 'Plomería'), ('ELE', 'Electricidad')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
