# Generated by Django 5.1.5 on 2025-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/'),
        ),
    ]
