# Generated by Django 5.1.5 on 2025-06-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0003_payment'),
        ('tecnico', '0002_alter_tecnico_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_averia', models.CharField(choices=[('electrica', 'Eléctrica'), ('agua', 'Agua'), ('wifi', 'Wi-Fi'), ('otro', 'Otro')], max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.department')),
            ],
        ),
        migrations.CreateModel(
            name='AveriaTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_resuelta', models.DateTimeField(auto_now_add=True)),
                ('averia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidents.averia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico')),
            ],
        ),
    ]
