# Generated by Django 5.1.5 on 2025-06-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averiatecnico',
            name='fecha_resuelta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
